Repository EmergSaver/MediQuick, pull requests merged in 2025-09, with the labels that each got.

#23 [FEATURE] 병원 상세 정보
  android/app/src/main/java/com/emergsaver/mediquick/DetailHospitalActivity.java
  android/app/src/main/java/model/Hospital.java
  android/app/src/main/java/model/Specialty.java
  android/app/src/main/java/nav/MapFragment.java
  android/app/src/main/java/repository/CongestionRepository.java
  android/app/src/main/java/repository/HospitalRepository.java
  android/app/src/main/java/util/CongestionManager.java
  android/app/src/main/java/util/MapManager.java
  android/app/src/main/res/drawable/ic_current.xml
  android/app/src/main/res/layout/activity_detail_hospital.xml
  android/app/src/main/res/layout/fragment_map.xml
Labels: design, feature, refactor

#26 UI/login
  android/app/src/main/java/com/emergsaver/mediquick/CheckEmail.java
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/LoginActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/ProfileFragment.java
  android/app/src/main/res/layout/activity_insert.xml
  android/app/src/main/res/layout/fragment_profile.xml
Labels: bug, design, feature

#33 [UI] 지도 및 병원 상세 페이지 ui 적용
  android/app/src/main/java/com/emergsaver/mediquick/DetailHospitalActivity.java
  android/app/src/main/java/util/MapManager.java
  android/app/src/main/res/drawable/black_marker.png
  android/app/src/main/res/drawable/btn_nav.xml
  android/app/src/main/res/drawable/ic_arrow_back.xml
  android/app/src/main/res/drawable/ic_call.xml
  android/app/src/main/res/drawable/ic_document.xml
  android/app/src/main/res/drawable/ic_export.xml
  android/app/src/main/res/drawable/ic_people.xml
  android/app/src/main/res/drawable/ic_phone.xml
  android/app/src/main/res/drawable/rounded_table.xml
  android/app/src/main/res/drawable/rounded_table_header_left.xml
  android/app/src/main/res/drawable/rounded_table_header_right.xml
  android/app/src/main/res/drawable/rounded_table_left.xml
  android/app/src/main/res/drawable/rounded_table_right.xml
  android/app/src/main/res/layout/activity_detail_hospital.xml
  android/app/src/main/res/layout/fragment_map.xml
  android/app/src/main/res/values/colors.xml
Labels: design, feature

#36 [FEATURE] 병원 추천 페이지 로직 구현
  android/app/src/main/java/com/emergsaver/mediquick/adapter/CategoryAdapter.java
  android/app/src/main/java/com/emergsaver/mediquick/adapter/HospitalAdapter.java
  android/app/src/main/java/com/emergsaver/mediquick/adapter/MapSearchAdapter.java
  android/app/src/main/java/com/emergsaver/mediquick/search/SearchActivity.java
  android/app/src/main/java/model/Hospital.java
  android/app/src/main/java/nav/CategoryFragment.java
  android/app/src/main/java/nav/HospitalFragment.java
  android/app/src/main/java/util/MapManager.java
  android/app/src/main/res/drawable/icon_body.png
  android/app/src/main/res/drawable/icon_bone.png
  android/app/src/main/res/drawable/icon_breath.png
  android/app/src/main/res/drawable/icon_digestion.png
  android/app/src/main/res/drawable/icon_eyes.png
  android/app/src/main/res/drawable/icon_general.png
  android/app/src/main/res/drawable/icon_heart.png
  android/app/src/main/res/drawable/icon_mouth_neck_face.png
  android/app/src/main/res/drawable/icon_poison.png
  android/app/src/main/res/drawable/icon_pregnancy.png
  android/app/src/main/res/drawable/icon_skin.png
  android/app/src/main/res/drawable/icon_urinary.png
  android/app/src/main/res/layout/fragment_category.xml
  android/app/src/main/res/layout/fragment_hospital.xml
  android/app/src/main/res/layout/item_hospital.xml
Labels: design, feature

#38 [BUGFIXED] 병원 추천
  android/app/src/main/java/nav/HospitalFragment.java
  android/app/src/main/res/layout/fragment_category.xml
  android/app/src/main/res/layout/fragment_hospital.xml
Labels: bug_fixed

#39 [FEAT] SPLASH 화면
  android/.idea/deploymentTargetSelector.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/emergsaver/mediquick/AllergyDialog.java
  android/app/src/main/java/com/emergsaver/mediquick/LogoutActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/SplashActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/adapter/HospitalAdapter.java
  android/app/src/main/java/com/emergsaver/mediquick/adapter/MapSearchAdapter.java
  android/app/src/main/res/layout/activity_agree_term.xml
  android/app/src/main/res/layout/activity_change_pass.xml
  android/app/src/main/res/layout/activity_check_email.xml
  android/app/src/main/res/layout/activity_delete_users.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_logout.xml
  android/app/src/main/res/layout/activity_signup.xml
  android/app/src/main/res/layout/activity_splash.xml
  android/app/src/main/res/layout/fragment_map.xml
  android/app/src/main/res/layout/fragment_profile.xml
  android/app/src/main/res/layout/fragment_user.xml
  android/app/src/main/res/layout/item_hospital.xml
  android/app/src/main/res/layout/item_recom_hospital.xml
Labels: enhancement, design, bug_fixed
