Repository EmergSaver/MediQuick, pull requests merged in 2025-08, with the labels that each got.

#4 [UI] 병원 로그인, 회원가입 UI 생성
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/LoginActivity.java
  android/app/src/main/res/layout/activity_insert.xml
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/layout/activity_main.xml
Labels: design

#5 [UI] 사용자 프로필 UI
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/emergsaver/mediquick/AllergyActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/EditProfileActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/ProfileActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/UploadPhotoActivity.java
  android/app/src/main/res/drawable/ic_profile_placeholder.png
  android/app/src/main/res/drawable/rounded_background.xml
  android/app/src/main/res/layout/activity_allergy.xml
  android/app/src/main/res/layout/activity_edit_profile.xml
  android/app/src/main/res/layout/activity_profile.xml
  android/app/src/main/res/layout/activity_upload_photo.xml
Labels: design

#6 [FEATURE] API 호출
  android/.gitignore
Labels: feature

#7 [UI]회원가입 기능구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/emergsaver/mediquick/AgreeTermActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/res/layout/activity_agree_term.xml
  android/app/src/main/res/layout/activity_insert.xml
  android/app/src/main/res/values/strings.xml
Labels: design, feature

#8 Db/logindb
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/res/layout/activity_agree_term.xml
  android/app/src/main/res/xml/network_security_config.xml
  android/build.gradle
Labels: feature

#9 Feature/login
  android/app/google-services.json
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/res/layout/activity_insert.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: design

#11 [🔧 LITTLE_FIX] 프로필 수정 및 알레르기 수정 기능
  android/app/src/main/java/com/emergsaver/mediquick/AllergyDialog.java
  android/app/src/main/java/com/emergsaver/mediquick/EditProfilePhotoDialog.java
  android/app/src/main/java/com/emergsaver/mediquick/ProfileFragment.java
  android/app/src/main/res/drawable/circular_background.xml
  android/app/src/main/res/layout/custom_spinner_item.xml
  android/app/src/main/res/layout/fragment_allergy_dialog.xml
  android/app/src/main/res/layout/fragment_edit_profile_photo_dialog.xml
Labels: feature

#14 Feature/email
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/emergsaver/mediquick/CheckEmail.java
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/LoginActivity.java
  android/app/src/main/res/layout/activity_check_email.xml
Labels: bug, design, feature

#15 [⚙️ FEAT] 회원가입시 성별, 전화번호 입력추가
  android/app/src/main/java/com/emergsaver/mediquick/InsertActivity.java
  android/app/src/main/res/layout/activity_insert.xml
Labels: feature

#18 [⚙️ FEAT] 증상 카테고리 화면 구현
  android/app/src/main/java/com/emergsaver/mediquick/MainActivity.java
  android/app/src/main/java/com/emergsaver/mediquick/adapter/CategoryAdapter.java
  android/app/src/main/java/com/emergsaver/mediquick/search/SearchActivity.java
  android/app/src/main/java/model/Category.java
  android/app/src/main/java/nav/CategoryFragment.java
  android/app/src/main/java/nav/HospitalFragment.java
  android/app/src/main/res/drawable/bg_dialog_rounded.xml
  android/app/src/main/res/drawable/icon_brain.png
  android/app/src/main/res/drawable/icon_nose.png
  android/app/src/main/res/drawable/search_circle_bg.xml
  android/app/src/main/res/layout/activity_search.xml
  android/app/src/main/res/layout/dialog_searchpopup.xml
  android/app/src/main/res/layout/fragment_category.xml
  android/app/src/main/res/layout/item_category.xml
  android/app/src/main/res/values/colors.xml
Labels: feature
